- Adding check for image url to be pushed

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -76,7 +76,7 @@ jobs:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         run: |
           echo "IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$(aws ecr describe-images --repository-name poss11111 --query \
-          'sort_by(imageDetails,& imagePushedAt)[-1]' | jq -r '.[0].imageTags[0]')" >> $GITHUB_ENV
+          'sort_by(imageDetails,& imagePushedAt)[-1]' | jq -r '.imageTags[0]')" >> $GITHUB_ENV
 
       - name: Build, tag, and push Clash-Bot image to Amazon ECR
         if: steps.check-apps.outputs.srcCode == 'true'
@@ -88,6 +88,13 @@ jobs:
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
           echo "IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV
+
+      - name: Check image to be pushed
+        run: |
+          if [[ $IMAGE =~ ^$ECR_REGISTRY\/$ECR_REPOSITORY:.*$ ]]; then
+            echo "Invalid Image Url"
+            exit 1
+          fi
 
       - name: Image Build Failed Discord Webhook
         uses: Poss111/discord-hook-action@v1.6.8
@@ -139,7 +146,7 @@ jobs:
           TF_VAR_three: ${{ secrets.THREE }}
           TF_VAR_four: ${{ secrets.FOUR }}
           TF_VAR_release_title : ${{ steps.vars.outputs.tag }}
-        run: terraform apply -input=false
+        run: terraform apply -auto-apply -input=false
 
       - name: Terraform Output
         working-directory: tfe
